config/routes.rb
Hiex::Application.routes.draw do

  root :to => 'public#index'
  match 'signup' => 'public#signup', :as => :sign_up #[REMOVEIT]
  match 'test2' => 'public#index', :as => :login #[REMOVEIT]
  match 'test3' => 'public#index', :as => :comatose_root #[REMOVEIT]

  resources :public do
    collection do
      get 'resources'
      get 'browse'
      get 'browse_form'
      get 'results'

      get 'contact'
      get 'signup'
    end
  end

end

app/views/layouts/_header.html.erb
		<div id="divHeader">
      <%= link_to image_tag("logo.jpg", :alt => "Logo", :class => "fleft", :border => 0), root_url %>
			<ul id="ulTopMenu">
				<li><%= link_to "Signout", logout_url, :id => "lnkSignout" %></li>
<% if current_user.has_role?('admin') %>
        <li class="li"><%= link_to "Settings", {:controller => "administrators", :action => "show", :id => current_user}, :id => "lnkSettings"  %></li>
<% elsif current_user.has_role?('sales_person') %>
        <li class="li"><%= link_to "Settings", sales_person_path(current_user.sales_person), :id => "lnkSettings" %></li>
<% elsif current_user.has_role?('contractor') %>
        <li class="li"><%= link_to "Settings", contractor_path(current_user.contractor), :id => "lnkSettings" %></li>
<% end %>
				<li class="li"><b>Welcome, <%= current_user.greeting_name %></b></li>
			</ul>
			<% if !current_user.has_role?('admin') && current_user.has_role?('contractor') %>
			<div id="topSalesInfo">
				<% if current_user.contractor.sales_person %>
			Sales person: <b><%=h current_user.contractor.sales_person.name %></b><br />phone: <b><%=h current_user.contractor.sales_person.phone %></b><br />email: <b><%= link_to current_user.contractor.sales_person.email, "mailto: #{current_user.contractor.sales_person.email}" %></b>
			<% end %>
			</div>
			<% end %>
			
		</div>

app/views/layouts/_navigation.html.erb
<% ########### LOGIC FOR TABS ############# %>
<% # TODO: Encapsulate this in a better way %>
<% if current_user.has_role?('admin') || current_user.has_role?('sales_person') %>
	<% tabPeople = (params[:controller] == "sales_people" || params[:controller] == "contractors" || params[:controller] == "administrators") || params[:controller] == "leads" || params[:controller] == "monopolies" %>
	<% tabOrders = (params[:controller] == "orders" || params[:controller] == "payments" || params[:controller] == "commissions_payments" || params[:controller] == "bonuses") %>
	<% tabTools = (params[:controller] == "zip_codes" || params[:controller] == "categories" || params[:controller] == "project_types" || params[:controller] == "questionnaires" || params[:controller] == "questions" || params[:controller] == "newsletters" || params[:controller] == "settings") %>
	<% tabReports = (params[:controller] == "comatose_admin") %>
	<% tabWishLists = (params[:controller] == "wish_lists") %>
<% elsif current_user.has_role?('contractor') %>

<% tabZipCodes = (params[:controller] == "zip_codes" || params[:controller] == "monopolies" || params[:controller] == "wish_lists") %>
<% tabLeads = (params[:controller] == "leads") %>
<% tabPayments = (params[:controller] == "payments") %>

<% end %>
      <ul id="ulTabMenu">
<% ######################### ADMIN and SALES_PERSON ######################### %>
<% if current_user.has_role?('admin') || current_user.has_role?('sales_person') %>
				<li class="<%= tabPeople ? "liSelected" : "liNotSelected" %>"><%= link_to "People", contractors_url %></li>
				<li class="<%= tabOrders ? "liSelected" : "liNotSelected" %>"><%= link_to "Orders", orders_path %></li>
				<li class="<%= tabTools ? "liSelected" : "liNotSelected" %>"><%= link_to "Tools", :controller => "zip_codes", :action => "search" %></li>
				<li class="<%= tabReports ? "liSelected" : "liNotSelected" %>"><%= link_to "CMS", comatose_admin_path %></li>
				<li class="liWishList<%= tabWishLists ? "" : "" %>"><%= link_to "<span class=\"WishListActive\">#{@active_wish_lists_count} Active</span> Wish Lists", :controller => "wish_lists", :action => "index" %>   
</li>
  <% if current_user.has_role?('admin') %>
<li class="liWishList"><%= link_to "<span class=\"WishListActive\">#{@pending_orders_count} Pending</span> Orders", :controller => "orders", :action => "index", :order_status_filter => 'pending', :date_filter => 'all' %>
</li>
<li class="liWishList"><%= link_to "<span class=\"WishListActive\">#{@expiring_orders_count} Expiring</span> Orders", :controller => "orders", :action => "index", :order_status_filter => '', :sort_key => 'orders.end_date', :sort_order => 'asc', :date_filter => 'all' %>
</li>
  <% end %>
<% ######################### CONTRACTOR ########################### %>
<% elsif current_user.has_role?('contractor') %>
				<li class="<%= tabLeads ? "liSelected" : "liNotSelected" %>"><%= link_to "Leads", leads_path %></li>

        <li class="<%= tabZipCodes ? "liSelected" : "liNotSelected" %>"><%= link_to "Zip Codes", contractor_monopolies_path(current_user.contractor) %></li>
        <li class="<%= tabPayments ? "liSelected" : "liNotSelected" %>"><%= link_to "Payments", payments_path %></li>
		<% if @expiring_monopolies_count > 0%>
        <li class="liWishList"><%= link_to "<span class=\"WishListActive\">#{@expiring_monopolies_count} Expiring</span>  Zip Codes!", contractor_monopolies_path(current_user.contractor) %></li>
		<% end %>
        <% if current_user.contractor.insurance_expiring? %>
        <li class="liWishList"><%= link_to "<span class=\"WishListActive\">Insurance Expiring!</span>", contractor_path(current_user.contractor) %></li>
        
        <% end %>
        
<% end %>
		  </ul>
<% if tabPeople %>
			<ul id="ulSubMenu">
			<% if current_user.has_role?('admin') %>
			  <li class="li<%= " liSelected" if params[:controller] == "sales_people" %>"><%= link_to "Salespeople", sales_people_url, :class => "aSelected" %></li>
			  <li class="li<%= " liSelected" if params[:controller] == "contractors" %>"><%= link_to "Contractors", contractors_url %></li>
              <li class="li<%= " liSelected" if params[:controller] == "administrators" %>"><%= link_to "Administrators", :controller => "administrators", :action => "index" %></li>
			  <li class="li<%= " liSelected" if params[:controller] == "leads" %>"><%= link_to "Leads", leads_url %></li>
			  <li class="li<%= " liSelected" if params[:controller] == "monopolies" && params[:action] == "index" %>"><%= link_to "Contractors Zips", monopolies_path %></li>
			  <li class="<%= "liSelected" if params[:controller] == "contractors" && params[:action] == "expirations" %>"><%= link_to "Contractors Expiring Zips", contractor_expirations_path %></li>
			  
			<% elsif current_user.has_role?('sales_person') %>
  			    <li class="li<%= " liSelected" if params[:controller] == "contractors" %>"><%= link_to "Contractors", contractors_url %></li>
                            <li class="li<%= " liSelected" if params[:controller] == "leads" %>"><%= link_to "Leads", leads_url %></li>
			    <li class="<%= "liSelected" if params[:controller] == "contractors" && params[:action] == "expirations" %>"><%= link_to "Contractors Expiring Zips", contractor_expirations_path %></li>

			<% end %>
			</ul>
<% elsif (current_user.has_role?('admin') || current_user.has_role?('sales_person')) && tabTools %>
      <ul id="ulSubMenu">
        <li class="li<%= " liSelected" if params[:controller] == "zip_codes" && params[:action] == "search" %>"><%= link_to "Zip Codes", :controller => "zip_codes", :action => "search" %></li>
        <% if current_user.has_role?('admin') %>
				<li class="li<%= " liSelected" if params[:controller] == "categories" || params[:controller] == "project_types" || params[:controller] == "questionnaires" || params[:controller] == "questions" %>"><%= link_to "Categories", :controller => "categories", :action => "index" %></li>
<li class="li<%= " liSelected" if params[:controller] == "newsletters" %>"><%= link_to "Newsletters", :controller => "newsletters", :action => "new" %></li>
<li class="li<%= " liSelected" if params[:controller] == "settings" %>"><%= link_to "System Settings", settings_path %></li>
<li class="li<%= " liSelected" if params[:controller] == "zip_codes" && params[:action] != "search" %>"><%= link_to "Edit Zip Codes", zip_codes_path %></li>

        <% end %>
      </ul>
<% elsif tabOrders %>
      <ul id="ulSubMenu">
      	<li class="li<%= " liSelected" if params[:controller] == "orders" && params[:action] == "index" %>"><%= link_to "Manage", orders_path %></li>
				<li class="li<%= " liSelected" if params[:action] == "new" || params[:action] == "create" %>"><%= link_to "New", new_order_path %></li>
<%   if current_user.has_role?('admin') %>
        <li class="li<%= " liSelected" if params[:controller] == "payments" && params[:action] == "index" %>"><%= link_to "Payment History", payments_path %></li>
<%   end %>
      	<li class="li<%= " liSelected" if params[:controller] == "commissions_payments" && params[:action] == "index" %>"><%= link_to "Commissions Paid", commissions_payments_path %></li>
<%   if current_user.has_role?('admin') %>
  <li class="li<%= " liSelected" if params[:controller] == "bonuses" %>"><%= link_to "Bonus Manager", bonuses_path %></li>
<%   end %>
      </ul>
<% elsif current_user.has_role?("contractor") && tabZipCodes %>

       <ul id="ulSubMenu">
         <li class="li<%= " liSelected" if params[:controller] == "monopolies" %>"><%= link_to "My Zip Codes", contractor_monopolies_path(current_user.contractor) %></li>
         <li class="li<%= " liSelected" if params[:controller] == "wish_lists" %>"><%= link_to "My Wishlist", contractor_wish_list_path(current_user.contractor, :show)  %></li>
         <li class="li<%= " liSelected" if params[:controller] == "zip_codes" %>"><%= link_to "Find more Zip Codes", :controller => "zip_codes", :action => "search" %></li>
         <li class="li"><%= link_to "Preview result page", {:controller => "public", :action => "results", :contractor_id => current_user.contractor}, :target => "_blank" %></li>
       </ul>
<% else %>
      <ul id="ulSubMenu"></ul>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Home Improvement Expo - <%= @title %></title>
  <%= stylesheet_link_tag 'administrator' %>
	<%= stylesheet_link_tag 'tree.css' %>

<% # Include TinyMCE before other JS to avoid problems -%>
<%= javascript_include_tiny_mce_if_used %>
<%= tiny_mce if using_tiny_mce? %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "yahoo-min.js" %>
  <%= javascript_include_tag "event-min.js" %>
  <%= javascript_include_tag "treeview-min.js" %>
  <%= calendar_date_select_includes  %>
  
</head>
<body>
<div id="divBody">
<%= render :partial => './layouts/header' %>

		<div id="divContent">

<%= render :partial => './layouts/navigation' %>
			
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:error] %></p>

<%= yield  %>
  </div>
  <div id="divFooter">
			<div id="divFeatureRequest">
				Request a new feature! 
				<a href="mailto: sales@homeimprovementexpo.com">Click Here</a>
			</div>
			&copy;<%= Date.today.year %> Contractor Services Network. All rights reserved.
			<%= link_to "Terms of Use", comatose_root_url(:page => "terms"), :class => "lnkPrivacy eleRightBorder" %>
            <%= link_to "Privacy Policy", comatose_root_url(:page => "privacy"), :class => "lnkPrivacy" %>
		</div>
</div>
</body>
</html>

app/views/layouts/admin.printer.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title><%= @title %></title>
  <%= stylesheet_link_tag 'administrator' %>

  
<!-- IE7 -->
<!-- compliance patch for microsoft browsers -->
<!--[if IE]><%= javascript_include_tag "ie7/ie7-standard-p" %><![endif]-->
</head>
<body onload="window.print();">
<%= yield :layout %>	
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hiex</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Categories: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= stylesheet_link_tag 'tree.css' %>


  <%= javascript_include_tag "yahoo-min.js" %>
  <%= javascript_include_tag "event-min.js" %>
  <%= javascript_include_tag "treeview-min.js" %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />  
</head>
<body>
<%= yield %>
</body>
</html>

app/views/layouts/possible_responses.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>PossibleResponses: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/question_types.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>QuestionTypes: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/questionnaires.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Questionnaires: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/responses.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Responses: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><%= @title || "Find Local Licensed Contractors - Home Improvement Network" %></title>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="Description" content="<%= @meta_description || "Search for contractors near you. Get a no-obligation quote from a licensed, insured professional within 24 hours, guaranteed!" %>" />
<%= stylesheet_link_tag 'site' %>
<%# javascript_include_tag :defaults %>
<%= yield :head %>
<%= javascript_include_tag "utils" %>
<link rel="shortcut icon" href="/images/favicon.ico" />

<SCRIPT language="JavaScript" type="text/javascript">
<!-- Yahoo! Inc.
var ysm_accountid  = "1EVG8DJLTJM1KL24UH2O40R0B4G";
document.write("<SCR" + "IPT language='JavaScript' type='text/javascript' " 
+ "SRC=//" + "srv1.wa.marketingsolutions.yahoo.com" + "/script/ScriptServlet" + "?aid=" + 
ysm_accountid 
+ "></SCR" + "IPT>");
// -->
</SCRIPT>


</head>
<body>

<div align="center">
  
  <%= yield  %>
  
</div>
<div align="center"></div>	
  
<%= yield :tracking %>
  
  
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4821795-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
  
</body>
</html>

app/views/layouts/site_cms.html.erb
<% @title ||= "#{@page ? @page.title : @page_title} - HomeImprovementExpo.com" %>
<% @meta_description ||= "#{@page ? @page.title : @page_title} - Search for local contractors. Get matched to a prescreened, certified, insured contractor who will call you withn 24 hours, guaranteed." %>

<% @content_for_layout = capture do %>

<div align="center" class="center_bg">
  <div class="header_logo">
   <table width="794" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td width="419" height="106" rowspan="2" valign="top"><%= link_to image_tag("expo_header_left.gif", :alt => "Home Improvement Expo logo", :width => 419, :height => 106, :border => 0), :controller => :public, :action => :index %></td><td width="375" height="72" valign="top"><%= image_tag "expo_header_right.gif", :alt => "Find a local contractor by contacting us!", :width => 375, :height => 72, :border => 0 %></td>
    </tr>
    <tr>
      <td align="right" valign="middle" class="menu_top"><%= link_to "Home", :controller => :public, :action => :index %>&nbsp;&nbsp;<%= link_to "About Us", comatose_root_url(:page => "about"), :rel => "nofollow" %>&nbsp;&nbsp;<%= link_to "Contact Us", {:controller => :public, :action => :contact}, :rel => "nofollow" %></td>
    </tr>
   </table>
  </div>
  <table width="100%" cellpadding="0" cellspacing="0">
    <tr>
      <td height="105" valign="top"><div align="center">
        <table width="754" cellspacing="0" cellpadding="0">
            <tr>
              <td valign="top" class="content_container">
               <table width="97%" align="center" cellpadding="0" cellspacing="0">
                <tr>
                  <td width="100%" height="60" class="page_title"><h1><%= @page ? @page.title : @page_title %></h1></td>
                </tr>
                <tr>
                  <td class="page_content">
                  	<% unless flash[:notice].blank? %>
					<span style="color: red"><b><%=h flash[:notice] %></b></span><br /><br />
					<% end %>
					
                	<%= yield :layout %>
					<% if @page && @page.parent && @page.parent.parent %>
					  <% if @page.parent.slug == "resource-center" %>
						<b><%= link_to "Back", :controller => "public", :action => "resources" %></b>
					  <% else %>
						<b><%= link_to "Back", comatose_root_url(:page => @page.parent.full_path) %></b>
					  <% end %>
					<% end %>
                  </td>
                </tr>
               </table>
              </td>
            </tr>
          </table>
		  <p>&nbsp;</p>
          <%= render :partial => './public/footer_menu' %>
      </div></td>
    </tr>
  </table>
  <table width="782" cellspacing="0" cellpadding="0">
    <tr bgcolor="#CBCBCB">
      <td height="1"></td>
    </tr>
    <tr>
      <td height="20"><div align="center"><span class="footer_grey">&nbsp;</span></div></td>
    </tr>
 <tr bgcolor="#CBCBCB">
      <td height="1"></td>
    </tr>
  </table>
  <br />
</div>
	
<% end %>


<%= render :inline => @content_for_layout,:layout => 'layouts/site'  %>



app/views/layouts/standard.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Hiex</title>
  <%#= stylesheet_link_tag 'scaffold' %>
  <%= stylesheet_link_tag 'style' %>
	<%= stylesheet_link_tag 'administrator' %>
  <%= javascript_include_tag :defaults %>
  <%= calendar_date_select_includes %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>